spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB


server:
  port: 8060
  servlet:
    context-path: /v1/public

# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头

dictionary:
  url: http://60.205.179.178:8050/Summer/v1/private/dictionary/query?word=

autumn:
  #  file: C:/image/
  file:
    uploadPath: C:/image/
#    uploadPath: /Users/guo/Downloads/autumn/
    accessPrefix: http://localhost:8060/
